--------------------------------------------------------
--  File created - Tuesday-July-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HPMLVMS"."EMPLOYEE" 
   (	"ID" NUMBER, 
	"EMP_NAME" CHAR(50 BYTE), 
	"DESIGNATION" CHAR(30 BYTE), 
	"EMP_CNIC" VARCHAR2(15 BYTE), 
	"DEPARTMENT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into HPMLVMS.EMPLOYEE
SET DEFINE OFF;
Insert into HPMLVMS.EMPLOYEE (ID,EMP_NAME,DESIGNATION,EMP_CNIC,DEPARTMENT_ID) values (3,'Inam                                              ','Executive                     ','4210165987456',4);
Insert into HPMLVMS.EMPLOYEE (ID,EMP_NAME,DESIGNATION,EMP_CNIC,DEPARTMENT_ID) values (4,'Inam                                              ','Executive                     ','4210165987456',4);
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPMLVMS"."EMPLOYEE_PK" ON "HPMLVMS"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HPMLVMS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
  ALTER TABLE "HPMLVMS"."EMPLOYEE" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HPMLVMS"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
