--------------------------------------------------------
--  File created - Tuesday-July-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISIT
--------------------------------------------------------

  CREATE TABLE "HPMLVMS"."VISIT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(15 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(15 BYTE), 
	"PURPOSE" VARCHAR2(150 BYTE), 
	"CNIC" VARCHAR2(15 BYTE), 
	"CONTACT_NO" VARCHAR2(11 BYTE), 
	"CHECKIN_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CHECKOUT_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"GENDER" VARCHAR2(15 BYTE), 
	"EMPLOYEE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into HPMLVMS.VISIT
SET DEFINE OFF;
Insert into HPMLVMS.VISIT (ID,NAME,ORGANIZATION_NAME,PURPOSE,CNIC,CONTACT_NO,CHECKIN_TIME,CHECKOUT_TIME,GENDER,EMPLOYEE_ID) values (221,'dfasd','dsfsd','Interview','sds','sdrwe',to_timestamp('26/07/2022 12:45:27 PM','DD/MM/RRRR fmHH:fmMI:SS AM'),to_timestamp('26/07/2022 12:45:00 PM','DD/MM/RRRR fmHH:fmMI:SS AM'),'male',4);
Insert into HPMLVMS.VISIT (ID,NAME,ORGANIZATION_NAME,PURPOSE,CNIC,CONTACT_NO,CHECKIN_TIME,CHECKOUT_TIME,GENDER,EMPLOYEE_ID) values (222,'asdasd','asdsad','Interview','dsadsa','asdsad',to_timestamp('26/07/2022 10:50:17 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),to_timestamp('09/07/2022 10:50:00 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),'male',4);
Insert into HPMLVMS.VISIT (ID,NAME,ORGANIZATION_NAME,PURPOSE,CNIC,CONTACT_NO,CHECKIN_TIME,CHECKOUT_TIME,GENDER,EMPLOYEE_ID) values (22,'sad','asda','Interview','ads','adsa',to_timestamp('26/07/2022 10:51:26 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),to_timestamp('01/07/2022 10:51:00 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),'female',4);
Insert into HPMLVMS.VISIT (ID,NAME,ORGANIZATION_NAME,PURPOSE,CNIC,CONTACT_NO,CHECKIN_TIME,CHECKOUT_TIME,GENDER,EMPLOYEE_ID) values (232,'asd','dsad','Interview','sad','sdad',to_timestamp('26/07/2022 10:49:08 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),to_timestamp('26/07/2022 3:49:00 PM','DD/MM/RRRR fmHH:fmMI:SS AM'),'female',4);
Insert into HPMLVMS.VISIT (ID,NAME,ORGANIZATION_NAME,PURPOSE,CNIC,CONTACT_NO,CHECKIN_TIME,CHECKOUT_TIME,GENDER,EMPLOYEE_ID) values (23,'asdaadasdd','Interview','asddasd','adasdasdsad','adsadsad',to_timestamp('26/07/2022 10:48:31 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),to_timestamp('26/07/2022 10:48:31 AM','DD/MM/RRRR fmHH:fmMI:SS AM'),'female',4);
--------------------------------------------------------
--  DDL for Index SYS_C00974146
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPMLVMS"."SYS_C00974146" ON "HPMLVMS"."VISIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table VISIT
--------------------------------------------------------

  ALTER TABLE "HPMLVMS"."VISIT" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "HPMLVMS"."VISIT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
  ALTER TABLE "HPMLVMS"."VISIT" MODIFY ("ID" NOT NULL ENABLE);
