# Generated by Django 4.0.5 on 2022-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('emp_cnic', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('cnic', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=13)),
                ('employee_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
    ]
